config/routes.rb
Filmbase::Application.routes.draw do
  resources :people

  resources :genres

  resources :countries

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :films

   root :to => "films#index"

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  has_many :films,:order=>'name'

  default_scope order('name')
  
  validates :name,:presence => true,:uniqueness => true

  def can_be_edited?(user)
    user && user.admin?
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_filter :check_admin_user,:except => 'show'

  def index
    @genres = Genre.all
  end

  def show
    @genre=@current_genre = Genre.includes(:films).find(params[:id])
  end

  def new
    @genre = Genre.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(params[:genre])

    if @genre.save
      redirect_to(@genre, :notice => 'Жанр создан.')
    else
      render :action => "new"
    end
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update_attributes(params[:genre])
      redirect_to(@genre, :notice => 'Жанр сохранен.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to genres_url, :notice=>"Жанр удален"
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.haml
=form_for @genre do |f|
  -if @genre.errors.any?
    .msg.error
      %h2= "При сохранении произошли ошибки"
      %ul
        - @genre.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit

app/views/genres/edit.html.haml
%h1 Редактирование жанра
= render 'form'
= link_to 'Показать', @genre
\|
= link_to 'Назад', genres_path

app/views/genres/index.html.haml
%h1 Жанры

%table
  %thead
    %tr
      %th=Genre.human_attribute_name('name')
      %th
      %th
  %tbody
    - @genres.each do |genre|
      %tr
        %td=link_to genre.name,genre
        %td= link_to 'Редактировать', edit_genre_path(genre)
        %td= link_to 'Удалить', genre, :confirm => 'Вы уверены?', :method => :delete

%br

= link_to 'Добавить жанр', new_genre_path

app/views/genres/new.html.haml
%h1 Новый жанр
= render 'form'
= link_to 'Назад', genres_path

app/views/genres/show.html.haml
%h1=@genre.name
-@genre.films.each do |film|
  =render 'films/film',:film=>film
-if @genre.can_be_edited?(@current_user)
  = link_to 'Редактировать', edit_genre_path(@genre)
  \|
= link_to 'Назад', genres_path